/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectof;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author esct
 */
public class ConsultaLV extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaLV
     */
    public ConsultaLV() {
        initComponents();
        pTabla();
    }
    
    private void pTabla() {
        String encabezado[] = {"Titulo", "Cantidad", "Subtotal", "Fecha"};
        DefaultTableModel t = new DefaultTableModel(encabezado, ProyectoF.librosvs.size());
        jTable1.setModel(t);
        TableModel tabla = jTable1.getModel();

        for (int i = 0; i < ProyectoF.librosvs.size(); i++) {
            LibroV lv = ProyectoF.librosvs.get(i);
            tabla.setValueAt(lv.getTitulo(), i, 0);
            tabla.setValueAt(lv.getCantidad(), i, 1);
            tabla.setValueAt(lv.getSubtotal(), i, 2);
            tabla.setValueAt(lv.getFecha(), i, 3);
        }
    }
    
    public void escrivirCsv(String ruta){
        try {
            FileWriter archivo = new FileWriter(ruta);
            PrintWriter escribir = new PrintWriter(archivo);
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                escribir.write("Titulo:" + jTable1.getModel().getValueAt(i, 0).toString()+", ");
                escribir.write("Cantidad:" +jTable1.getModel().getValueAt(i, 1).toString()+", ");
                escribir.write("Subtotal:" +jTable1.getModel().getValueAt(i, 2).toString()+", ");
                escribir.write("Fecha:" +jTable1.getModel().getValueAt(i, 3).toString()+"\n");
            }
            escribir.close();
            archivo.close();
            JOptionPane.showMessageDialog(this, "Reporte creado exitosamente");
        } catch (IOException ex) {
            Logger.getLogger(V_Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Reporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Reporte.setText("Crear Reporte");
        Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Reporte)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(Reporte)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteActionPerformed
        // TODO add your handling code here:
        
        escrivirCsv("LibrosVendidos.csv");
    }//GEN-LAST:event_ReporteActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
