/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectof;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author esct
 */
public class V_Admin extends javax.swing.JFrame {

    Programa prog = new Programa();
    /**
     * Creates new form V_Admin
     */
    public V_Admin() {
        initComponents();
    }
    
    public static void escribirArchivoBinario(Object o, String ruta){
        try{
            FileOutputStream archivo = new FileOutputStream(ruta);
            ObjectOutputStream escribe = new ObjectOutputStream(archivo);
            escribe.writeObject(o);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public static Object leerArchivoBinario(String ruta){
        try{
            FileInputStream archivo = new FileInputStream(ruta);
            ObjectInputStream lee = new ObjectInputStream(archivo);
            return lee.readObject();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return null;
    }
    
    public static void InsertarDatos(){
        Programa leeido = (Programa)leerArchivoBinario("Info.progra");
        
        for(Usuario u : leeido.getUsuar()){
            Usuario us = new Usuario();
            us.setNombre(u.getNombre());
            us.setPassword(u.getPassword());
            us.setRol(u.getRol());
            us.setUsuario(u.getUsuario());
            ProyectoF.usuarios.add(us);
        }
        
        for(Libro l : leeido.getLibr()){
            Libro li = new Libro();
            li.setTitulo(l.getTitulo());
            li.setGenero(l.getGenero());
            li.setAutor(l.getAutor());
            li.setPrecio(l.getPrecio());
            li.setStock(l.getStock());
            ProyectoF.libros.add(li);
        }
        
        for(Cupon c : leeido.getCupo()){
            Cupon cu = new Cupon();
            cu.setCodigo(c.getCodigo());
            cu.setTipo(c.getTipo());
            cu.setValor(c.getValor());
            cu.setVencimineto(c.getVencimineto());
            cu.setDisponible(c.getDisponible());
            ProyectoF.cupones.add(cu);
        }
        
        for(Venta v : leeido.getVent()){
            Venta ve = new Venta();
            ve.setNit(v.getNit());
            ve.setNombre(v.getNombre());
            ve.setDireccion(v.getDireccion());
            ve.setVendedor(v.getVendedor());
            ve.setTotal(v.getTotal());
            ve.setTotalSinIva(v.getTotalSinIva());
            ve.setFecha(v.getFecha());
            ve.setLibrosV(v.getLibrosV());
            ProyectoF.ventas.add(ve);
        }
        
        for(Proveedor p: leeido.getProvee()){
            Proveedor pr = new Proveedor();
            pr.setNit(p.getNit());
            pr.setDireccion(p.getDireccion());
            pr.setTelefono(p.getTelefono());
            pr.setNombre(p.getNombre());
            ProyectoF.proveedores.add(pr);
        }
        
        for(LibroV lv : leeido.getLibrv()){
            LibroV liv = new LibroV();
            liv.setTitulo(lv.getTitulo());
            liv.setCantidad(lv.getCantidad());
            liv.setSubtotal(lv.getSubtotal());
            liv.setFecha(lv.getFecha());
            ProyectoF.librosvs.add(liv);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LeerArchivo = new javax.swing.JButton();
        EscribirArchivo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Bienvenido administrador");

        LeerArchivo.setText("Leer");
        LeerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerArchivoActionPerformed(evt);
            }
        });

        EscribirArchivo.setText("Escribir");
        EscribirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirArchivoActionPerformed(evt);
            }
        });

        jMenu1.setText("Usuario");

        jMenuItem6.setText("Crear");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem1.setText("Consultar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Libros");

        jMenuItem3.setText("Agregar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem2.setText("Consultar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem10.setText("Vendidos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cupones");

        jMenuItem4.setText("Crear");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Consultar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ventas");

        jMenuItem7.setText("Consultar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Proveedores");

        jMenuItem8.setText("Agregar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Consultar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(LeerArchivo)
                        .addGap(18, 18, 18)
                        .addComponent(EscribirArchivo)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LeerArchivo)
                    .addComponent(EscribirArchivo))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ConsultaU c = new ConsultaU();
        c.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ConsultaL c = new ConsultaL();
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        LibroNuevo ln = new LibroNuevo();
        ln.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CuponNuevo cn = new CuponNuevo();
        cn.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ConsultaC cc = new ConsultaC();
        cc.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        UsuarioNuevo n = new UsuarioNuevo();
        n.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        ConsultarV cv = new ConsultarV();
        cv.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        ProveedorNuevo pn = new ProveedorNuevo();
        pn.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        ConsultarP cp = new ConsultarP();
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        ConsultaLV clv = new ConsultaLV();
        clv.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void LeerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerArchivoActionPerformed
        // TODO add your handling code here:
        InsertarDatos();
        
    }//GEN-LAST:event_LeerArchivoActionPerformed

    private void EscribirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirArchivoActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Usuario> usuario = new ArrayList<>();
        for(Usuario u : ProyectoF.usuarios){
            Usuario us = new Usuario();
            us.setNombre(u.getNombre());
            us.setPassword(u.getPassword());
            us.setRol(u.getRol());
            us.setUsuario(u.getUsuario());
            us.setTelefonos(u.getTelefonos());
            usuario.add(us);
        }
        
        ArrayList<Libro> libro = new ArrayList<>();
        for(Libro l : ProyectoF.libros){
            Libro li = new Libro();
            li.setTitulo(l.getTitulo());
            li.setAutor(l.getAutor());
            li.setGenero(l.getGenero());
            li.setPrecio(l.getPrecio());
            li.setStock(l.getStock());
            libro.add(li);
        }
        
        ArrayList<Cupon> cupon = new ArrayList<>();
        for(Cupon c : ProyectoF.cupones){
            Cupon cu = new Cupon();
            cu.setCodigo(c.getCodigo());
            cu.setValor(c.getValor());
            cu.setVencimineto(c.getVencimineto());
            cu.setTipo(c.getTipo());
            cu.setDisponible(c.getDisponible());
            cupon.add(cu);
        }
        
        ArrayList<Venta> venta = new ArrayList<>();
        for(Venta v : ProyectoF.ventas){
            Venta ve = new Venta();
            ve.setNit(v.getNit());
            ve.setNombre(v.getNombre());
            ve.setDireccion(v.getDireccion());
            ve.setVendedor(v.getVendedor());
            ve.setTotal(v.getTotal());
            ve.setTotalSinIva(v.getTotalSinIva());
            ve.setFecha(v.getFecha());
            ve.setLibrosV(v.getLibrosV());
            venta.add(ve);
        }
        
        ArrayList<Proveedor> proveedor = new ArrayList<>();
        for(Proveedor p : ProyectoF.proveedores){
            Proveedor pr = new Proveedor();
            pr.setNit(p.getNit());
            pr.setNombre(p.getNombre());
            pr.setTelefono(p.getTelefono());
            pr.setDireccion(p.getDireccion());
            proveedor.add(pr);
        }
        
        ArrayList<LibroV> librov = new ArrayList<>();
        for(LibroV lv : ProyectoF.librosvs){
            LibroV liv = new LibroV();
            liv.setTitulo(lv.getTitulo());
            liv.setCantidad(lv.getCantidad());
            liv.setSubtotal(lv.getSubtotal());
            liv.setFecha(lv.getFecha());
            librov.add(liv);
        }
        
        prog.setUsuar(usuario);
        prog.setLibr(libro);
        prog.setCupo(cupon);
        prog.setVent(venta);
        prog.setProvee(proveedor);
        prog.setLibrv(librov);
        
        if (JOptionPane.showConfirmDialog(this, "Desea Guardar los cambios") == 0){
            escribirArchivoBinario(prog, "Info.progra");
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        }
    }//GEN-LAST:event_EscribirArchivoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EscribirArchivo;
    private javax.swing.JButton LeerArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
